export const PICK_FIELDS = [
  "clubId",
  "leagueId",
  "countryId",
  "versionId",

  "rating",
  "preferredFoot",
  "skillMoves",
  "preferredPosition",
  "possiblePositions",
  "playStyles",
  "playStylesPlus",
  "rolesPlus",
  "rolesPlusPlus",

  "attributes",

  "isObjective",
  "hasDynamicImage",
  "sbcPrice",
  "price",
];

export const EN_TO_DE_COUNTRIES = {
  Germany: "Deutschland",
  England: "England",
  Wales: "Wales",
  Scotland: "Schottland",
  France: "Frankreich",
  Spain: "Spanien",
  Italy: "Italien",
  Portugal: "Portugal",
  Netherlands: "Niederlande",
  Belgium: "Belgien",
  Austria: "Österreich",
  Switzerland: "Schweiz",
  Poland: "Polen",
  "Czech Republic": "Tschechien",
  Slovakia: "Slowakei",
  Hungary: "Ungarn",
  Denmark: "Dänemark",
  Norway: "Norwegen",
  Sweden: "Schweden",
  Finland: "Finnland",
  Iceland: "Island",
  Ireland: "Irland",
  "Republic of Ireland": "Irland",
  "Northern Ireland": "Nordirland",
  "Bosnia and Herzegovina": "Bosnien und Herzegowina",
  Serbia: "Serbien",
  Croatia: "Kroatien",
  Slovenia: "Slowenien",
  "North Macedonia": "Nordmazedonien",
  Montenegro: "Montenegro",
  Albania: "Albanien",
  Greece: "Griechenland",
  Turkey: "Türkei",
  Russia: "Russland",
  Ukraine: "Ukraine",
  Belarus: "Belarus",
  Moldova: "Moldau",
  Romania: "Rumänien",
  Bulgaria: "Bulgarien",
  Armenia: "Armenien",
  Azerbaijan: "Aserbaidschan",
  Georgia: "Georgien",
  Kazakhstan: "Kasachstan",
  "Saudi Arabia": "Saudi-Arabien",
  "United Arab Emirates": "Vereinigte Arabische Emirate",
  Qatar: "Katar",
  Bahrain: "Bahrain",
  Kuwait: "Kuwait",
  Oman: "Oman",
  Iran: "Iran",
  Iraq: "Irak",
  Israel: "Israel",
  Jordan: "Jordanien",
  Lebanon: "Libanon",
  Syria: "Syrien",
  Morocco: "Marokko",
  Algeria: "Algerien",
  Tunisia: "Tunesien",
  Egypt: "Ägypten",
  Libya: "Libyen",
  Sudan: "Sudan",
  "South Sudan": "Südsudan",
  "Côte d'Ivoire": "Elfenbeinküste",
  "Ivory Coast": "Elfenbeinküste",
  Ghana: "Ghana",
  Nigeria: "Nigeria",
  Senegal: "Senegal",
  Cameroon: "Kamerun",
  Congo: "Kongo",
  "DR Congo": "Demokratische Republik Kongo",
  "Democratic Republic of the Congo": "Demokratische Republik Kongo",
  Guinea: "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Burkina Faso": "Burkina Faso",
  Mali: "Mali",
  Niger: "Niger",
  Gabon: "Gabun",
  Benin: "Benin",
  Togo: "Togo",
  Angola: "Angola",
  Mozambique: "Mosambik",
  Zambia: "Sambia",
  Zimbabwe: "Simbabwe",
  "South Africa": "Südafrika",
  "Cape Verde": "Kap Verde",
  "Cabo Verde": "Kap Verde",
  "Central African Republic": "Zentralafrikanische Republik",
  "Equatorial Guinea": "Äquatorialguinea",
  Ethiopia: "Äthiopien",
  Eritrea: "Eritrea",
  Somalia: "Somalia",
  Kenya: "Kenia",
  Tanzania: "Tansania",
  Uganda: "Uganda",
  Rwanda: "Ruanda",
  Burundi: "Burundi",
  Botswana: "Botswana",
  Namibia: "Namibia",
  Madagascar: "Madagaskar",
  Mauritania: "Mauretanien",
  Mauritius: "Mauritius",
  Spain: "Spanien",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Monaco: "Monaco",
  Liechtenstein: "Liechtenstein",
  "United States": "Vereinigte Staaten",
  USA: "Vereinigte Staaten",
  Canada: "Kanada",
  Mexico: "Mexiko",
  "Costa Rica": "Costa Rica",
  Panama: "Panama",
  Honduras: "Honduras",
  Guatemala: "Guatemala",
  "El Salvador": "El Salvador",
  Nicaragua: "Nicaragua",
  "Dominican Republic": "Dominikanische Republik",
  Haiti: "Haiti",
  Jamaica: "Jamaika",
  "Trinidad and Tobago": "Trinidad und Tobago",
  Argentina: "Argentinien",
  Brazil: "Brasilien",
  Uruguay: "Uruguay",
  Chile: "Chile",
  Colombia: "Kolumbien",
  Peru: "Peru",
  Paraguay: "Paraguay",
  Ecuador: "Ecuador",
  Venezuela: "Venezuela",
  Bolivia: "Bolivien",
  Australia: "Australien",
  "New Zealand": "Neuseeland",
  Japan: "Japan",
  "South Korea": "Südkorea",
  "Korea Republic": "Südkorea",
  "Korea, Republic of": "Südkorea",
  "North Korea": "Nordkorea",
  "Korea DPR": "Nordkorea",
  China: "China",
  "Hong Kong": "Hongkong",
  Taiwan: "Taiwan",
  Thailand: "Thailand",
  Vietnam: "Vietnam",
  Indonesia: "Indonesien",
  Malaysia: "Malaysia",
  Singapore: "Singapur",
  Philippines: "Philippinen",
  India: "Indien",
  Pakistan: "Pakistan",
  Bangladesh: "Bangladesch",
  "Sri Lanka": "Sri Lanka",
  Nepal: "Nepal",
  Mongolia: "Mongolei",
  Cambodia: "Kambodscha",
  Laos: "Laos",
  Myanmar: "Myanmar",
  "New Caledonia": "Neukaledonien",
  "Papua New Guinea": "Papua-Neuguinea",
  Fiji: "Fidschi",
  Gibraltar: "Gibraltar",
  "Faroe Islands": "Färöer",
  Greenland: "Grönland",
  Kosovo: "Kosovo",
  Morocco: "Marokko",
  Tunisia: "Tunesien",
  Algeria: "Algerien",
  Portugal: "Portugal",
  "United Kingdom": "Vereinigtes Königreich",
  Scotland: "Schottland",
  Wales: "Wales",
  England: "England",
  "Northern Ireland": "Nordirland",
  Turkey: "Türkei",
  Luxembourg: "Luxemburg",
  Lithuania: "Litauen",
  Latvia: "Lettland",
  Estonia: "Estland",
  Malta: "Malta",
  Cyprus: "Zypern",
  Iraq: "Irak",
  Iran: "Iran",
  "Saudi Arabia": "Saudi-Arabien",
  UAE: "Vereinigte Arabische Emirate",
  Qatar: "Katar",
};

export const PREFERREDCOUNTRIES = {
  Deutschland: 1,
  Österreich: 2,
  Schweiz: 3,
  Brasilien: 4,
  Argentinien: 5,
  England: 6,
  Niederlande: 7,
  Belgien: 8,
  Frankreich: 9,
  Spanien: 10,
  Portugal: 11,
  Italien: 12,
  Tschechien: 13,
  Polen: 14,
  Dänemark: 15,
};

export const COUNTRYID_FOR_LEAGUEID = {
  1: { cId: 13, sortId: 37 },
  4: { cId: 7, sortId: 30 },
  10: { cId: 34, sortId: 25 },
  13: { cId: 14, sortId: 8 },
  14: { cId: 14, sortId: 9 },
  16: { cId: 18, sortId: 19 },
  17: { cId: 18, sortId: 20 },
  19: { cId: 21, sortId: 1 },
  20: { cId: 21, sortId: 2 },
  31: { cId: 27, sortId: 16 },
  32: { cId: 27, sortId: 17 },
  39: { cId: 95, sortId: 22 },
  41: { cId: 36, sortId: 35 },
  50: { cId: 42, sortId: 31 },
  53: { cId: 45, sortId: 13 },
  54: { cId: 45, sortId: 14 },
  56: { cId: 46, sortId: 34 },
  60: { cId: 14, sortId: 10 },
  61: { cId: 14, sortId: 11 },
  63: { cId: 22, sortId: 36 },
  65: { cId: 25, sortId: 33 },
  66: { cId: 37, sortId: 28 },
  68: { cId: 48, sortId: 26 },
  80: { cId: 4, sortId: 5 },
  83: { cId: 166, sortId: 43 },
  189: { cId: 47, sortId: 6 },
  308: { cId: 38, sortId: 27 },
  317: { cId: 10, sortId: 38 },
  319: { cId: 12, sortId: 29 },
  322: { cId: 17, sortId: 39 },
  330: { cId: 39, sortId: 40 },
  332: { cId: 49, sortId: 41 },
  350: { cId: 183, sortId: 24 },
  351: { cId: 195, sortId: 42 },
  353: { cId: 52, sortId: 44 },
  1003: { cId: 54, sortId: 45 },
  1014: { cId: 54, sortId: 46 },
  2012: { cId: 155, sortId: 47 },
  2076: { cId: 21, sortId: 3 },
  2149: { cId: 159, sortId: 48 },
  2172: { cId: 190, sortId: 49 },
  2209: { cId: 56, sortId: 50 },
  2210: { cId: 11, sortId: 51 },
  2211: { cId: 23, sortId: 52 },
  2215: { cId: 21, sortId: 4 },
  2216: { cId: 14, sortId: 12 },
  2218: { cId: 18, sortId: 21 },
  2221: { cId: 95, sortId: 23 },
  2222: { cId: 45, sortId: 15 },
  2228: { cId: 38, sortId: 53 },
  2229: { cId: 34, sortId: 54 },
  2230: { cId: 12, sortId: 55 },
  2231: { cId: 47, sortId: 7 },
  2232: { cId: 46, sortId: 56 },
  2233: { cId: 42, sortId: 32 },
  2236: { cId: 27, sortId: 18 },
  2244: { cId: 5, sortId: 57 },
};

export const BASE_VERSION_IDS = new Set([
  "2000",
  "2001",
  "2002",
  "3000",
  "3001",
  "3002",
]);