export const PICK_FIELDS = [
  "clubId",
  "leagueId",
  "countryId",
  "versionId",

  "rating",
  "preferredFoot",
  "skillMoves",
  "preferredPosition",
  "possiblePositions",
  "playStyles",
  "playStylesPlus",
  "rolesPlus",
  "rolesPlusPlus",

  "attributes",

  "isObjective",
  "hasDynamicImage",
  "sbcPrice",
  "price",
];

export const EN_TO_DE_COUNTRIES = {
  Germany: "Deutschland",
  England: "England",
  Wales: "Wales",
  Scotland: "Schottland",
  France: "Frankreich",
  Spain: "Spanien",
  Italy: "Italien",
  Portugal: "Portugal",
  Netherlands: "Niederlande",
  Belgium: "Belgien",
  Austria: "Österreich",
  Switzerland: "Schweiz",
  Poland: "Polen",
  "Czech Republic": "Tschechien",
  Slovakia: "Slowakei",
  Hungary: "Ungarn",
  Denmark: "Dänemark",
  Norway: "Norwegen",
  Sweden: "Schweden",
  Finland: "Finnland",
  Iceland: "Island",
  Ireland: "Irland",
  "Republic of Ireland": "Irland",
  "Northern Ireland": "Nordirland",
  "Bosnia and Herzegovina": "Bosnien und Herzegowina",
  Serbia: "Serbien",
  Croatia: "Kroatien",
  Slovenia: "Slowenien",
  "North Macedonia": "Nordmazedonien",
  Montenegro: "Montenegro",
  Albania: "Albanien",
  Greece: "Griechenland",
  Turkey: "Türkei",
  Russia: "Russland",
  Ukraine: "Ukraine",
  Belarus: "Belarus",
  Moldova: "Moldau",
  Romania: "Rumänien",
  Bulgaria: "Bulgarien",
  Armenia: "Armenien",
  Azerbaijan: "Aserbaidschan",
  Georgia: "Georgien",
  Kazakhstan: "Kasachstan",
  "Saudi Arabia": "Saudi-Arabien",
  "United Arab Emirates": "Vereinigte Arabische Emirate",
  Qatar: "Katar",
  Bahrain: "Bahrain",
  Kuwait: "Kuwait",
  Oman: "Oman",
  Iran: "Iran",
  Iraq: "Irak",
  Israel: "Israel",
  Jordan: "Jordanien",
  Lebanon: "Libanon",
  Syria: "Syrien",
  Morocco: "Marokko",
  Algeria: "Algerien",
  Tunisia: "Tunesien",
  Egypt: "Ägypten",
  Libya: "Libyen",
  Sudan: "Sudan",
  "South Sudan": "Südsudan",
  "Côte d'Ivoire": "Elfenbeinküste",
  "Ivory Coast": "Elfenbeinküste",
  Ghana: "Ghana",
  Nigeria: "Nigeria",
  Senegal: "Senegal",
  Cameroon: "Kamerun",
  Congo: "Kongo",
  "DR Congo": "Demokratische Republik Kongo",
  "Democratic Republic of the Congo": "Demokratische Republik Kongo",
  Guinea: "Guinea",
  "Guinea-Bissau": "Guinea-Bissau",
  "Burkina Faso": "Burkina Faso",
  Mali: "Mali",
  Niger: "Niger",
  Gabon: "Gabun",
  Benin: "Benin",
  Togo: "Togo",
  Angola: "Angola",
  Mozambique: "Mosambik",
  Zambia: "Sambia",
  Zimbabwe: "Simbabwe",
  "South Africa": "Südafrika",
  "Cape Verde": "Kap Verde",
  "Cabo Verde": "Kap Verde",
  "Central African Republic": "Zentralafrikanische Republik",
  "Equatorial Guinea": "Äquatorialguinea",
  Ethiopia: "Äthiopien",
  Eritrea: "Eritrea",
  Somalia: "Somalia",
  Kenya: "Kenia",
  Tanzania: "Tansania",
  Uganda: "Uganda",
  Rwanda: "Ruanda",
  Burundi: "Burundi",
  Botswana: "Botswana",
  Namibia: "Namibia",
  Madagascar: "Madagaskar",
  Mauritania: "Mauretanien",
  Mauritius: "Mauritius",
  Spain: "Spanien",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Monaco: "Monaco",
  Liechtenstein: "Liechtenstein",
  "United States": "Vereinigte Staaten",
  USA: "Vereinigte Staaten",
  Canada: "Kanada",
  Mexico: "Mexiko",
  "Costa Rica": "Costa Rica",
  Panama: "Panama",
  Honduras: "Honduras",
  Guatemala: "Guatemala",
  "El Salvador": "El Salvador",
  Nicaragua: "Nicaragua",
  "Dominican Republic": "Dominikanische Republik",
  Haiti: "Haiti",
  Jamaica: "Jamaika",
  "Trinidad and Tobago": "Trinidad und Tobago",
  Argentina: "Argentinien",
  Brazil: "Brasilien",
  Uruguay: "Uruguay",
  Chile: "Chile",
  Colombia: "Kolumbien",
  Peru: "Peru",
  Paraguay: "Paraguay",
  Ecuador: "Ecuador",
  Venezuela: "Venezuela",
  Bolivia: "Bolivien",
  Australia: "Australien",
  "New Zealand": "Neuseeland",
  Japan: "Japan",
  "South Korea": "Südkorea",
  "Korea Republic": "Südkorea",
  "Korea, Republic of": "Südkorea",
  "North Korea": "Nordkorea",
  "Korea DPR": "Nordkorea",
  China: "China",
  "Hong Kong": "Hongkong",
  Taiwan: "Taiwan",
  Thailand: "Thailand",
  Vietnam: "Vietnam",
  Indonesia: "Indonesien",
  Malaysia: "Malaysia",
  Singapore: "Singapur",
  Philippines: "Philippinen",
  India: "Indien",
  Pakistan: "Pakistan",
  Bangladesh: "Bangladesch",
  "Sri Lanka": "Sri Lanka",
  Nepal: "Nepal",
  Mongolia: "Mongolei",
  Cambodia: "Kambodscha",
  Laos: "Laos",
  Myanmar: "Myanmar",
  "New Caledonia": "Neukaledonien",
  "Papua New Guinea": "Papua-Neuguinea",
  Fiji: "Fidschi",
  Gibraltar: "Gibraltar",
  "Faroe Islands": "Färöer",
  Greenland: "Grönland",
  Kosovo: "Kosovo",
  Morocco: "Marokko",
  Tunisia: "Tunesien",
  Algeria: "Algerien",
  Portugal: "Portugal",
  "United Kingdom": "Vereinigtes Königreich",
  Scotland: "Schottland",
  Wales: "Wales",
  England: "England",
  "Northern Ireland": "Nordirland",
  Turkey: "Türkei",
  Luxembourg: "Luxemburg",
  Lithuania: "Litauen",
  Latvia: "Lettland",
  Estonia: "Estland",
  Malta: "Malta",
  Cyprus: "Zypern",
  Iraq: "Irak",
  Iran: "Iran",
  "Saudi Arabia": "Saudi-Arabien",
  UAE: "Vereinigte Arabische Emirate",
  Qatar: "Katar",
};

export const PREFERREDCOUNTRIES = {
  Deutschland: 1,
  Österreich: 2,
  Schweiz: 3,
  Brasilien: 4,
  Argentinien: 5,
  England: 6,
  Niederlande: 7,
  Belgien: 8,
  Frankreich: 9,
  Spanien: 10,
  Portugal: 11,
  Italien: 12,
  Tschechien: 13,
  Polen: 14,
  Dänemark: 15,
};
